project_id = "tffrgsaawvletgiztfry"

[functions.generate-mentor-content]
verify_jwt = false

[functions.generate-mentor-audio]
verify_jwt = false

[functions.generate-mentor-script]
verify_jwt = false

[functions.generate-full-mentor-audio]
verify_jwt = false